name: artifact
on: push

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo hihihihi dongmin37 > dm37.txt
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact-test
          path: ./dm37.txt
  download-artifact:
    runs-on: ubuntu-latest
    needs: [upload-artifact]
    steps:
      - name: download arfifact
        uses: actions/download-artifact@v3
        with:
          name: artifact-test
          path: ./
      - name: check
        run: cat dm37.txt
